base_url = "https://poetry.blog"
title = "Poetry Blog"
description = "A minimal poetry blog built with Zola"
default_language = "en"

compile_sass = true
minify_html = true
hard_link_static = false

build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
render_emoji = true

[extra]
author = "Poetry Lover"